osx_image: xcode10.1
language: swift
cache:
  - bundler
  - cocoapods
git:
  depth: 3
install:
  - bundle install
jobs:
  include:
    - stage: unit-tests
      name: "Run unit tests"
      script: fastlane unit_tests