osx_image: xcode10
language: swift
cache: cocoapods
git:
  depth: 3
xcode_workspace: BSWInterfaceKit.xcworkspace
xcode_scheme: BSWInterfaceKitDemo
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 7