name: Swift

on:
  push
  
jobs:
  build:

    runs-on: ios

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Test BSWInterfaceKit
      run: set -o pipefail && xcodebuild -scheme BSWInterfaceKit -destination "platform=iOS Simulator,name=iPhone 13,OS=16.4" -resultBundlePath TestResults.xcresult test | xcbeautify
